name: Release
on:
  workflow_dispatch:
    inputs:
      api_token:
        description: "Your reddit api_token."
        type: string
        required: true
      your_reddit_username:
        description: "Your reddit username."
        type: string
        required: true
      # remote_debug:
      #   description: >-
      #     Starts an SSH session to debug the runner. For advanced troubleshooting only.
      #   type: boolean
      #   required: false
      #   default: false

jobs:
  build: # This job will now handle both build and conditional release
    runs-on: ubuntu-latest
    env:
      api_token: ${{ inputs.api_token }}
      your_reddit_username: ${{ inputs.your_reddit_username }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0 # Fetch all history for tag creation, needed for git tag

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y jupyter-nbconvert

      - name: Start debug session (when enabled)
        if: ${{ inputs.remote_debug }}
        uses: lhotari/action-upterm@v1

      - name: Build
        run: |
          sudo api_token="$api_token" your_reddit_username="$your_reddit_username" python ./scripts/prepare.py
          sudo api_token="$api_token" your_reddit_username="$your_reddit_username" bash ./scripts/build.sh

      - name: Validate artifact
        run: test -f /content/Infinity.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Infinity
          path: /content/Infinity.apk
